create database Ulife;
use Ulife;

CREATE TABLE aluno(
COD_RA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (50) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
CPF INT(11) NOT NULL,
RG INT(20) NOT NULL,
CAMPUS VARCHAR (100) NOT NULL,
CURSO VARCHAR(50) NOT NULL,
UC VARCHAR(50) NOT NULL,
NUMERO_SALA INT(20) NOT NULL,
TURNO VARCHAR (20) NOT NULL,
CURSO_EXTENSIVO VARCHAR(100),
FREQUENCIA_ALUNO VARCHAR(100) ,
NOTAS INT (20),
GRADE_HORARIO VARCHAR(100) ,
EMAIL VARCHAR (250),
TELEFONE INT(20)
);

CREATE TABLE PROFESSOR(
ID_PROF INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME_PROFESSOR VARCHAR (50) NOT NULL,
SENHA VARCHAR(100) NOT NULL,
SALARIO VARCHAR(100) NOT NULL,
CAMPUS VARCHAR (100) NOT NULL,
DISCIPLINA VARCHAR(100) NOT NULL,
GRADE_HORARIA VARCHAR(100) NOT NULL,
TURMA varchar(30) NOT NULL,
NUMERO_SALA INT(20) NOT NULL
);

CREATE TABLE Sistema (
    ID_SISTEMA INT NOT NULL PRIMARY KEY AUTO_INCREMENt,
    NOME VARCHAR(50),
    VERSAO VARCHAR(20),
    DATA_LACAMENTO DATE
);
