
package a3;

import javax.swing.JButton;
import java.awt.Color;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import java.awt.Toolkit;


/**
 *
 * @author Pichau
 */
public class tela2 extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form tela2
	 */
	public tela2() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(tela2.class.getResource("/a3/555.jpg")));
		setTitle("Sorveteria Orland - Pedido");
		initComponents();
	}

	double total = 0;

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		rdbcreme = new javax.swing.JRadioButton();
		rdbbaunilha = new javax.swing.JRadioButton();
		rdbflocos = new javax.swing.JRadioButton();
		rdbmorango = new javax.swing.JRadioButton();
		rdbnapolitano = new javax.swing.JRadioButton();
		rdbvegano = new javax.swing.JRadioButton();
		rdbchocolate = new javax.swing.JRadioButton();
		jTextField1 = new javax.swing.JTextField();
		jTextField1.setEditable(false);
		jTextField2 = new javax.swing.JTextField();
		jTextField2.setEditable(false);
		btnconfirmarpedido = new javax.swing.JButton();
		btncopo = new javax.swing.JRadioButton();
		btncopo.setEnabled(false);
		jLabel2 = new javax.swing.JLabel();
		btncasca = new javax.swing.JRadioButton();
		btncasca.setEnabled(false);
		rdbcaramelocob = new javax.swing.JRadioButton();
		rdbcaramelocob.setEnabled(false);
		rdbmorangocob = new javax.swing.JRadioButton();
		rdbmorangocob.setEnabled(false);
		rdbdocedeleitecob = new javax.swing.JRadioButton();
		rdbdocedeleitecob.setEnabled(false);
		rdbchantillycob = new javax.swing.JRadioButton();
		rdbchantillycob.setEnabled(false);
		rdbchocolatecob = new javax.swing.JRadioButton();
		rdbchocolatecob.setEnabled(false);
		rdbleitecondensadocob = new javax.swing.JRadioButton();
		rdbleitecondensadocob.setEnabled(false);
		rdbgranuladocob = new javax.swing.JRadioButton();
		rdbgranuladocob.setEnabled(false);
		jLabel1 = new javax.swing.JLabel();
		lbltotal1 = new javax.swing.JLabel();
		btnlimpar1 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();

		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(51, 204, 255));

		rdbcreme.setText("Creme - R$ 2,00");
		rdbcreme.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbcremeActionPerformed(evt);
			}
		});

		rdbbaunilha.setText("Baunilha - R$ 2,00");
		rdbbaunilha.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbbaunilhaActionPerformed(evt);
			}
		});

		rdbflocos.setText("Flocos - R$ 2,00");
		rdbflocos.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbflocosActionPerformed(evt);
			}
		});

		rdbmorango.setText("Morango - R$ 2,00");
		rdbmorango.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbmorangoActionPerformed(evt);
			}
		});

		rdbnapolitano.setText("Napolitano - R$ 4,00");
		rdbnapolitano.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbnapolitanoActionPerformed(evt);
			}
		});

		rdbvegano.setText("Vegano - R$5,00");
		rdbvegano.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbveganoActionPerformed(evt);
			}
		});

		rdbchocolate.setText("Chocolate - R$2,00");
		rdbchocolate.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbchocolateActionPerformed(evt);
			}
		});

		jTextField1.setBackground(new java.awt.Color(51, 204, 255));
		jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		jTextField1.setText("      SABORES");
		jTextField1.setBorder(null);
		jTextField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// jTextField1ActionPerformed(evt);
			}
		});

		jTextField2.setBackground(new java.awt.Color(51, 204, 255));
		jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
		jTextField2.setText("   COBERTURAS");
		jTextField2.setBorder(null);
		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// jTextField2ActionPerformed(evt);
			}
		});

		btnconfirmarpedido.setBackground(new java.awt.Color(51, 204, 255));
		btnconfirmarpedido.setText("Confirmar pedido");
		btnconfirmarpedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnconfirmarpedido.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnconfirmarpedidoActionPerformed(evt);
			}
		});

		btncopo.setText("Copo - R$5,00");
		btncopo.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btncopoActionPerformed(evt);
			}
		});

		jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a3/casca.jpg"))); // NOI18N

		btncasca.setText("Casquinnha - R$7,00");
		btncasca.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btncascaActionPerformed(evt);
			}
		});

		rdbcaramelocob.setText("Caramelo - R$1,00");
		rdbcaramelocob.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbcaramelocobActionPerformed(evt);
			}
		});

		rdbmorangocob.setText("Morango - R$2,00");
		rdbmorangocob.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbmorangocobActionPerformed(evt);
			}
		});

		rdbdocedeleitecob.setText("Doce de Leite - R$5,00");
		rdbdocedeleitecob.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbdocedeleitecobActionPerformed(evt);
			}
		});

		rdbchantillycob.setText("Chantilly - R$2,00");
		rdbchantillycob.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbchantillycobActionPerformed(evt);
			}
		});

		rdbchocolatecob.setText("Chocolate - R$2,00");
		rdbchocolatecob.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbchocolatecobActionPerformed(evt);
			}
		});

		rdbleitecondensadocob.setText("Leite Condensado - R$5,00");
		rdbleitecondensadocob.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbleitecondensadocobActionPerformed(evt);
			}
		});

		rdbgranuladocob.setText("Granulado - R$4,00");
		rdbgranuladocob.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				rdbgranuladocobActionPerformed(evt);
			}
		});

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a3/copo.jpg"))); // NOI18N

		lbltotal1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
		lbltotal1.setForeground(new java.awt.Color(0, 204, 0));
		lbltotal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		lbltotal1.setToolTipText("");

		btnlimpar1.setBackground(new java.awt.Color(51, 204, 255));
		btnlimpar1.setText("Limpar");
		btnlimpar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
		btnlimpar1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnlimpar1ActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("TOTAL:");

		btnNewButton = new JButton("Finalizar Pedido");
		btnNewButton.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				tela3 Tela = new tela3();
				Tela.setVisible(true);
			}
		});
		btnNewButton.setBackground(new Color(0, 191, 255));

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.TRAILING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(15)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
										.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE)
										.addComponent(rdbnapolitano, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(rdbcreme, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(rdbbaunilha, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(rdbflocos, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE)
										.addComponent(rdbmorango, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(rdbvegano, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(rdbchocolate, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
									.addGap(91)
									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
										.addGroup(jPanel1Layout.createSequentialGroup()
											.addGap(6)
											.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
												.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
													.addComponent(rdbcaramelocob, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
													.addComponent(rdbmorangocob, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
													.addComponent(rdbdocedeleitecob, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
													.addComponent(rdbchantillycob, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
													.addComponent(rdbchocolatecob, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE))
												.addComponent(rdbgranuladocob, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
												.addComponent(rdbleitecondensadocob, GroupLayout.PREFERRED_SIZE, 196, GroupLayout.PREFERRED_SIZE)))))
								.addGroup(jPanel1Layout.createSequentialGroup()
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 104, GroupLayout.PREFERRED_SIZE)
									.addPreferredGap(ComponentPlacement.RELATED)
									.addComponent(lbltotal1, GroupLayout.PREFERRED_SIZE, 206, GroupLayout.PREFERRED_SIZE))))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(213)
							.addComponent(btnlimpar1, GroupLayout.PREFERRED_SIZE, 79, GroupLayout.PREFERRED_SIZE)))
					.addPreferredGap(ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(btncasca)
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
							.addComponent(jLabel1)
							.addComponent(jLabel2))
						.addComponent(btncopo)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGap(6)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addComponent(btnconfirmarpedido)
								.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 120, GroupLayout.PREFERRED_SIZE))))
					.addGap(71))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addGap(39)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(12)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(rdbcreme)
								.addComponent(rdbcaramelocob))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(rdbbaunilha)
								.addComponent(rdbmorangocob))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(rdbflocos)
								.addComponent(rdbdocedeleitecob))
							.addGap(12)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(rdbmorango)
								.addComponent(rdbchantillycob))
							.addGap(12)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(rdbnapolitano)
								.addComponent(rdbchocolatecob))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(rdbvegano)
								.addComponent(rdbleitecondensadocob))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(rdbchocolate)
								.addComponent(rdbgranuladocob))
							.addPreferredGap(ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
							.addComponent(btnlimpar1))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jLabel1)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btncopo)
							.addGap(15)
							.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 103, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.RELATED)
							.addComponent(btncasca)
							.addGap(18)
							.addComponent(btnconfirmarpedido)))
					.addGap(54)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(btnNewButton)
							.addGap(41))
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
							.addComponent(lbltotal1, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
							.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)))
					.addGap(64))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jPanel1,
				GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addComponent(jPanel1,
				GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>

	private void rdbveganoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbvegano.isSelected()) {
			rdbcreme.setSelected(false);
			rdbmorango.setSelected(false);
			rdbchocolate.setSelected(false);
			rdbflocos.setSelected(false);
			rdbbaunilha.setSelected(false);
			rdbnapolitano.setSelected(false);
			habilitarCampos();
			total = 5;

		}
	}

	private void rdbchocolateActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbchocolate.isSelected()) {
			rdbcreme.setSelected(false);
			rdbflocos.setSelected(false);
			rdbbaunilha.setSelected(false);
			rdbnapolitano.setSelected(false);
			rdbmorango.setSelected(false);
			rdbvegano.setSelected(false);
			habilitarCampos();
			total = 2;

		}
	}

	private void rdbcremeActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbcreme.isSelected()) {
			rdbchocolate.setSelected(false);
			rdbflocos.setSelected(false);
			rdbbaunilha.setSelected(false);
			rdbnapolitano.setSelected(false);
			rdbmorango.setSelected(false);
			rdbvegano.setSelected(false);
			habilitarCampos();
			total = 2;
		}
	}

	private void rdbbaunilhaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbbaunilha.isSelected()) {
			rdbcreme.setSelected(false);
			rdbflocos.setSelected(false);
			rdbchocolate.setSelected(false);
			rdbnapolitano.setSelected(false);
			rdbmorango.setSelected(false);
			rdbvegano.setSelected(false);
			habilitarCampos();
			total = 2;
		}
	}

	private void rdbflocosActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbflocos.isSelected()) {
			rdbcreme.setSelected(false);
			rdbmorango.setSelected(false);
			rdbchocolate.setSelected(false);
			rdbnapolitano.setSelected(false);
			rdbbaunilha.setSelected(false);
			rdbvegano.setSelected(false);
			habilitarCampos();
			total = 2;
		}
	}

	private void rdbmorangoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbmorango.isSelected()) {
			rdbcreme.setSelected(false);
			rdbflocos.setSelected(false);
			rdbchocolate.setSelected(false);
			rdbnapolitano.setSelected(false);
			rdbbaunilha.setSelected(false);
			rdbvegano.setSelected(false);
			habilitarCampos();
			total = 2;
		}
	}

	private void rdbnapolitanoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbnapolitano.isSelected()) {
			rdbcreme.setSelected(false);
			rdbmorango.setSelected(false);
			rdbchocolate.setSelected(false);
			rdbflocos.setSelected(false);
			rdbbaunilha.setSelected(false);
			rdbvegano.setSelected(false);
			habilitarCampos();
			total = 4;
		}
	}

	// inicio das coberturas

	private void rdbmorangocobActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbmorangocob.isSelected()) {
			total += 2;
		} else {
			total -= 2;
		}

	}

	private void rdbdocedeleitecobActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbdocedeleitecob.isSelected()) {
			total += 5;
		} else {
			total -= 5;
		}

	}

	private void rdbcaramelocobActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbcaramelocob.isSelected()) {
			total += 1;
		} else {
			total -= 1;
		}

	}

	private void rdbchantillycobActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbchantillycob.isSelected()) {
			total += 2;
		} else {
			total -= 2;
		}

	}

	private void rdbchocolatecobActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbchocolatecob.isSelected()) {
			total += 2;
		} else {
			total -= 2;
		}

	}

	private void rdbleitecondensadocobActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbleitecondensadocob.isSelected()) {
			total += 5;
		} else {
			total -= 5;
		}

	}

	private void rdbgranuladocobActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (rdbgranuladocob.isSelected()) {
			total += 4;
		} else {
			total -= 4;
		}

	}

	private void btncopoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (btncopo.isSelected()) {
			btncasca.setSelected(false);
			total += 5;
		} else {
			total -= 5;
		}

	}

	private void btncascaActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (btncasca.isSelected()) {
			btncopo.setSelected(false);
			total += 7;
		} else {
			total -= 7;
		}

	}

	private void btnconfirmarpedidoActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		lbltotal1.setText(String.valueOf("R$" + total));
	}

	private void btnlimpar1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		btncopo.setSelected(false);
		btncasca.setSelected(false);
		rdbchantillycob.setSelected(false);
		rdbmorangocob.setSelected(false);
		rdbchocolatecob.setSelected(false);
		rdbdocedeleitecob.setSelected(false);
		rdbcaramelocob.setSelected(false);
		rdbleitecondensadocob.setSelected(false);
		rdbgranuladocob.setSelected(false);
		rdbdocedeleitecob.setEnabled(true);
		rdbchocolatecob.setEnabled(true);
		rdbchantillycob.setEnabled(true);
		rdbmorangocob.setEnabled(true);
		rdbcaramelocob.setEnabled(true);
		rdbleitecondensadocob.setEnabled(true);
		rdbgranuladocob.setEnabled(true);
		rdbcreme.setSelected(false);
		rdbmorango.setSelected(false);
		rdbchocolate.setSelected(false);
		rdbnapolitano.setSelected(false);
		rdbbaunilha.setSelected(false);
		rdbflocos.setSelected(false);
		rdbvegano.setSelected(false);
		btncasca.setEnabled(false);
		btncopo.setEnabled(false);
		desabilitarCampos2();
		lbltotal1.setText(null);
	}

	private void habilitarCampos() {
		rdbdocedeleitecob.setEnabled(true);
		rdbchocolatecob.setEnabled(true);
		rdbchantillycob.setEnabled(true);
		rdbmorangocob.setEnabled(true);
		rdbcaramelocob.setEnabled(true);
		rdbleitecondensadocob.setEnabled(true);
		rdbgranuladocob.setEnabled(true);

		btncasca.setEnabled(true);
		btncopo.setEnabled(true);

	}

	private void desabilitarCampos2() {
		rdbdocedeleitecob.setEnabled(false);
		rdbchocolatecob.setEnabled(false);
		rdbchantillycob.setEnabled(false);
		rdbmorangocob.setEnabled(false);
		rdbcaramelocob.setEnabled(false);
		rdbleitecondensadocob.setEnabled(false);
		rdbgranuladocob.setEnabled(false);

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(tela2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new tela2().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JRadioButton btncasca;
	private javax.swing.JButton btnconfirmarpedido;
	private javax.swing.JRadioButton btncopo;
	private javax.swing.JButton btnlimpar1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JLabel lbltotal1;
	private javax.swing.JRadioButton rdbbaunilha;
	private javax.swing.JRadioButton rdbcaramelocob;
	private javax.swing.JRadioButton rdbchantillycob;
	private javax.swing.JRadioButton rdbchocolate;
	private javax.swing.JRadioButton rdbchocolatecob;
	private javax.swing.JRadioButton rdbcreme;
	private javax.swing.JRadioButton rdbdocedeleitecob;
	private javax.swing.JRadioButton rdbflocos;
	private javax.swing.JRadioButton rdbgranuladocob;
	private javax.swing.JRadioButton rdbleitecondensadocob;
	private javax.swing.JRadioButton rdbmorango;
	private javax.swing.JRadioButton rdbmorangocob;
	private javax.swing.JRadioButton rdbnapolitano;
	private javax.swing.JRadioButton rdbvegano;
	private JButton btnNewButton;
}